"""paridade soscalculos passo 1

Revision ID: 39d3f3e0e3aa
Revises: fe684f4ae656
Create Date: 2026-07-28 23:16:35.170554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39d3f3e0e3aa'
down_revision: Union[str, Sequence[str], None] = 'fe684f4ae656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correcao_segmento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vencimento_tipo', sa.Enum('DO_VENCIMENTO', 'DA_CITACAO', 'DA_DISTRIBUICAO', 'DA_SENTENCA', 'DO_EVENTO', 'DO_TRANSITO_JULGADO', 'DA_PUBLICACAO', 'DA_DATA_FIXA', 'DA_HOMOLOGACAO', 'DA_APOSENTADORIA', name='tipo_vencimento'), server_default='DO_VENCIMENTO', nullable=False))
        batch_op.add_column(sa.Column('permite_deflacao', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('compor_com_selic', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('juros_segmento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vencimento_tipo', sa.Enum('DO_VENCIMENTO', 'DA_CITACAO', 'DA_DISTRIBUICAO', 'DA_SENTENCA', 'DO_EVENTO', 'DO_TRANSITO_JULGADO', 'DA_PUBLICACAO', 'DA_DATA_FIXA', 'DA_HOMOLOGACAO', 'DA_APOSENTADORIA', name='tipo_vencimento'), server_default='DO_VENCIMENTO', nullable=False))

    with op.batch_alter_table('processo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrato', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('feito', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('exibir_relatorio_detalhado', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('exibir_relatorio_correcao', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('contagem_juros', sa.Enum('PRO_RATA', 'POR_COMPETENCIA', name='contagem_juros'), server_default='PRO_RATA', nullable=False))
        batch_op.add_column(sa.Column('data_citacao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_distribuicao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_sentenca', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_transito_julgado', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_publicacao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_fixa', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_homologacao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_aposentadoria', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_evento_padrao', sa.Date(), nullable=True))
        batch_op.alter_column('numero_processo',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('comarca',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('vara',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processo', schema=None) as batch_op:
        batch_op.alter_column('vara',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('comarca',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('numero_processo',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('data_evento_padrao')
        batch_op.drop_column('data_aposentadoria')
        batch_op.drop_column('data_homologacao')
        batch_op.drop_column('data_fixa')
        batch_op.drop_column('data_publicacao')
        batch_op.drop_column('data_transito_julgado')
        batch_op.drop_column('data_sentenca')
        batch_op.drop_column('data_distribuicao')
        batch_op.drop_column('data_citacao')
        batch_op.drop_column('contagem_juros')
        batch_op.drop_column('exibir_relatorio_correcao')
        batch_op.drop_column('exibir_relatorio_detalhado')
        batch_op.drop_column('feito')
        batch_op.drop_column('contrato')

    with op.batch_alter_table('juros_segmento', schema=None) as batch_op:
        batch_op.drop_column('vencimento_tipo')

    with op.batch_alter_table('correcao_segmento', schema=None) as batch_op:
        batch_op.drop_column('compor_com_selic')
        batch_op.drop_column('permite_deflacao')
        batch_op.drop_column('vencimento_tipo')

    # ### end Alembic commands ###
