"""multa percentual na parcela

Revision ID: 4a0986c594ca
Revises: 39d3f3e0e3aa
Create Date: 2026-07-28 23:54:07.042809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.tipos


# revision identifiers, used by Alembic.
revision: str = '4a0986c594ca'
down_revision: Union[str, Sequence[str], None] = '39d3f3e0e3aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcela', schema=None) as batch_op:
        batch_op.add_column(sa.Column('multa_percentual', app.models.tipos.DecimalText(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcela', schema=None) as batch_op:
        batch_op.drop_column('multa_percentual')

    # ### end Alembic commands ###
