"""salario minimo valor

Revision ID: af3c682d5ed7
Revises: 9a808774c5aa
Create Date: 2026-07-29 13:32:22.823135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.tipos


# revision identifiers, used by Alembic.
revision: str = 'af3c682d5ed7'
down_revision: Union[str, Sequence[str], None] = '9a808774c5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salario_minimo_valor',
    sa.Column('competencia', sa.Date(), nullable=False),
    sa.Column('valor', app.models.tipos.DecimalText(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competencia', name='uq_salario_minimo_valor_competencia')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salario_minimo_valor')
    # ### end Alembic commands ###
