"""schema inicial desktop

Revision ID: dd00a3f879e8
Revises: 
Create Date: 2026-07-28 17:12:53.403388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.tipos

# revision identifiers, used by Alembic.
revision: str = 'dd00a3f879e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indice_serie_valor',
    sa.Column('indice', sa.Enum('IPCA', 'IPCA_E', 'INPC', 'IGP_M', 'IGP_DI', 'SELIC_SIMPLES', 'SELIC_COMPOSTA', 'TR', 'TBF', 'TLP', 'POUPANCA', 'PTAX', 'SALARIO_MINIMO', 'TRIBUNAL', 'PIS_PASEP', 'SEM_CORRECAO', name='indice'), nullable=False),
    sa.Column('tribunal_codigo', sa.String(), server_default='', nullable=False),
    sa.Column('competencia', sa.Date(), nullable=False),
    sa.Column('variacao_percentual', app.models.tipos.DecimalText(), nullable=False),
    sa.Column('fonte', sa.Enum('BCB_SGS', 'IBGE', 'MANUAL', name='fonte_indice'), nullable=False),
    sa.Column('importado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('superseded_por', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('indice_serie_valor', schema=None) as batch_op:
        batch_op.create_index('uq_indice_competencia_tribunal_ativo', ['indice', 'competencia', 'tribunal_codigo'], unique=True, sqlite_where=sa.text('superseded_por IS NULL'), postgresql_where=sa.text('superseded_por IS NULL'))

    op.create_table('processo',
    sa.Column('numero_processo', sa.String(), nullable=False),
    sa.Column('requerente', sa.String(), nullable=False),
    sa.Column('requerido', sa.String(), nullable=False),
    sa.Column('comarca', sa.String(), nullable=False),
    sa.Column('vara', sa.String(), nullable=False),
    sa.Column('data_calculo', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acessorio',
    sa.Column('processo_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('HONORARIOS_SUCUMBENCIA', 'MULTA_523_CPC', 'HONORARIOS_523_CPC', 'HONORARIOS_CONTRATUAIS', 'HONORARIOS_EXECUCAO', 'MULTA', 'CUSTAS_PROCESSUAIS', name='tipo_acessorio'), nullable=False),
    sa.Column('percentual', app.models.tipos.DecimalText(), nullable=True),
    sa.Column('valor_fixo', app.models.tipos.DecimalText(), nullable=True),
    sa.Column('base_calculo', sa.Enum('TOTAL_LIQUIDO_PARCELAS', 'VALOR_PRINCIPAL_SEM_CORRECAO', 'VALOR_FIXO_ABSOLUTO', name='base_calculo_acessorio'), nullable=False),
    sa.Column('data_evento', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(percentual IS NOT NULL AND valor_fixo IS NULL) OR (percentual IS NULL AND valor_fixo IS NOT NULL)', name='ck_acessorio_percentual_xor_valor_fixo'),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acessorio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acessorio_processo_id'), ['processo_id'], unique=False)

    op.create_table('calculo_execucao',
    sa.Column('processo_id', sa.Uuid(), nullable=False),
    sa.Column('data_calculo', sa.Date(), nullable=False),
    sa.Column('valor_total_apurado', app.models.tipos.DecimalText(), nullable=False),
    sa.Column('hash_conteudo', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calculo_execucao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calculo_execucao_processo_id'), ['processo_id'], unique=False)

    op.create_table('parcela',
    sa.Column('processo_id', sa.Uuid(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('historico', sa.String(), nullable=False),
    sa.Column('valor_bruto', app.models.tipos.DecimalText(), nullable=False),
    sa.Column('valor_pago', app.models.tipos.DecimalText(), nullable=True),
    sa.Column('valor_pago_data', sa.Date(), nullable=True),
    sa.Column('valor_apurado', app.models.tipos.DecimalText(), nullable=True),
    sa.Column('usa_correcao_default', sa.Boolean(), nullable=False),
    sa.Column('usa_juros_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('valor_pago IS NULL OR valor_pago_data IS NOT NULL', name='ck_parcela_valor_pago_requer_data'),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parcela', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parcela_processo_id'), ['processo_id'], unique=False)

    op.create_table('correcao_segmento',
    sa.Column('dono_tipo', sa.Enum('PROCESSO_DEFAULT', 'PARCELA_OVERRIDE', name='dono_tipo'), nullable=False),
    sa.Column('processo_id', sa.Uuid(), nullable=True),
    sa.Column('parcela_id', sa.Uuid(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('indice', sa.Enum('IPCA', 'IPCA_E', 'INPC', 'IGP_M', 'IGP_DI', 'SELIC_SIMPLES', 'SELIC_COMPOSTA', 'TR', 'TBF', 'TLP', 'POUPANCA', 'PTAX', 'SALARIO_MINIMO', 'TRIBUNAL', 'PIS_PASEP', 'SEM_CORRECAO', name='indice'), nullable=False),
    sa.Column('tribunal_codigo', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(processo_id IS NOT NULL AND parcela_id IS NULL) OR (processo_id IS NULL AND parcela_id IS NOT NULL)', name='ck_correcao_segmento_dono_exclusivo'),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcela.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correcao_segmento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correcao_segmento_parcela_id'), ['parcela_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_correcao_segmento_processo_id'), ['processo_id'], unique=False)

    op.create_table('juros_segmento',
    sa.Column('dono_tipo', sa.Enum('PROCESSO_DEFAULT', 'PARCELA_OVERRIDE', name='dono_tipo'), nullable=False),
    sa.Column('processo_id', sa.Uuid(), nullable=True),
    sa.Column('parcela_id', sa.Uuid(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('tipo_taxa', sa.Enum('PERCENTUAL_FIXO_MENSAL', 'TAXA_LEGAL', 'SELIC_SUBSTITUTIVA', name='tipo_taxa_juros'), nullable=False),
    sa.Column('taxa_valor', app.models.tipos.DecimalText(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("tipo_taxa <> 'percentual_fixo_mensal' OR taxa_valor IS NOT NULL", name='ck_juros_segmento_taxa_valor_obrigatorio'),
    sa.CheckConstraint('(processo_id IS NOT NULL AND parcela_id IS NULL) OR (processo_id IS NULL AND parcela_id IS NOT NULL)', name='ck_juros_segmento_dono_exclusivo'),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcela.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('juros_segmento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_juros_segmento_parcela_id'), ['parcela_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_juros_segmento_processo_id'), ['processo_id'], unique=False)

    op.create_table('memoria_calculo',
    sa.Column('parcela_id', sa.Uuid(), nullable=False),
    sa.Column('calculo_execucao_id', sa.Uuid(), nullable=False),
    sa.Column('competencia', sa.Date(), nullable=False),
    sa.Column('saldo_inicio_mes', app.models.tipos.DecimalText(), nullable=False),
    sa.Column('indice_aplicado', sa.Enum('IPCA', 'IPCA_E', 'INPC', 'IGP_M', 'IGP_DI', 'SELIC_SIMPLES', 'SELIC_COMPOSTA', 'TR', 'TBF', 'TLP', 'POUPANCA', 'PTAX', 'SALARIO_MINIMO', 'TRIBUNAL', 'PIS_PASEP', 'SEM_CORRECAO', name='indice'), nullable=True),
    sa.Column('variacao_indice', app.models.tipos.DecimalText(), nullable=False),
    sa.Column('saldo_corrigido', app.models.tipos.DecimalText(), nullable=False),
    sa.Column('taxa_juros_aplicada', app.models.tipos.DecimalText(), nullable=False),
    sa.Column('juros_mes', app.models.tipos.DecimalText(), nullable=False),
    sa.Column('saldo_final_mes', app.models.tipos.DecimalText(), nullable=False),
    sa.Column('parada_ativa', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['calculo_execucao_id'], ['calculo_execucao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcela.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memoria_calculo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memoria_calculo_calculo_execucao_id'), ['calculo_execucao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memoria_calculo_parcela_id'), ['parcela_id'], unique=False)

    op.create_table('parada_extraordinaria',
    sa.Column('processo_id', sa.Uuid(), nullable=True),
    sa.Column('parcela_id', sa.Uuid(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.Column('suspende_correcao', sa.Boolean(), nullable=False),
    sa.Column('suspende_juros', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(processo_id IS NOT NULL AND parcela_id IS NULL) OR (processo_id IS NULL AND parcela_id IS NOT NULL)', name='ck_parada_dono_exclusivo'),
    sa.CheckConstraint('data_fim >= data_inicio', name='ck_parada_data_fim_apos_inicio'),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcela.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parada_extraordinaria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parada_extraordinaria_parcela_id'), ['parcela_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parada_extraordinaria_processo_id'), ['processo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parada_extraordinaria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parada_extraordinaria_processo_id'))
        batch_op.drop_index(batch_op.f('ix_parada_extraordinaria_parcela_id'))

    op.drop_table('parada_extraordinaria')
    with op.batch_alter_table('memoria_calculo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memoria_calculo_parcela_id'))
        batch_op.drop_index(batch_op.f('ix_memoria_calculo_calculo_execucao_id'))

    op.drop_table('memoria_calculo')
    with op.batch_alter_table('juros_segmento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_juros_segmento_processo_id'))
        batch_op.drop_index(batch_op.f('ix_juros_segmento_parcela_id'))

    op.drop_table('juros_segmento')
    with op.batch_alter_table('correcao_segmento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correcao_segmento_processo_id'))
        batch_op.drop_index(batch_op.f('ix_correcao_segmento_parcela_id'))

    op.drop_table('correcao_segmento')
    with op.batch_alter_table('parcela', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parcela_processo_id'))

    op.drop_table('parcela')
    with op.batch_alter_table('calculo_execucao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calculo_execucao_processo_id'))

    op.drop_table('calculo_execucao')
    with op.batch_alter_table('acessorio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acessorio_processo_id'))

    op.drop_table('acessorio')
    op.drop_table('processo')
    with op.batch_alter_table('indice_serie_valor', schema=None) as batch_op:
        batch_op.drop_index('uq_indice_competencia_tribunal_ativo', sqlite_where=sa.text('superseded_por IS NULL'), postgresql_where=sa.text('superseded_por IS NULL'))

    op.drop_table('indice_serie_valor')
    # ### end Alembic commands ###
