"""memoria calculo aceita acessorio

Revision ID: fe684f4ae656
Revises: 619d9c58a5ff
Create Date: 2026-07-28 21:36:39.622633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe684f4ae656'
down_revision: Union[str, Sequence[str], None] = '619d9c58a5ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memoria_calculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acessorio_id', sa.Uuid(), nullable=True))
        batch_op.alter_column('parcela_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_memoria_calculo_acessorio_id'), ['acessorio_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_memoria_calculo_acessorio_id_acessorio', 'acessorio', ['acessorio_id'], ['id'], ondelete='CASCADE'
        )
        batch_op.create_check_constraint(
            'ck_memoria_calculo_dono_exclusivo',
            "(parcela_id IS NOT NULL AND acessorio_id IS NULL) OR "
            "(parcela_id IS NULL AND acessorio_id IS NOT NULL)",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memoria_calculo', schema=None) as batch_op:
        batch_op.drop_constraint('ck_memoria_calculo_dono_exclusivo', type_='check')
        batch_op.drop_constraint('fk_memoria_calculo_acessorio_id_acessorio', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_memoria_calculo_acessorio_id'))
        batch_op.alter_column('parcela_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)
        batch_op.drop_column('acessorio_id')

    # ### end Alembic commands ###
